require 'faker'

@voter1 = Voter.create(name: "Bill", age: 25, ethnicity: "Irish", registered_party: "Democrat", username: "Bill123", password: "123bill", role: 0)
@voter2 = Voter.create(name: "Bob", age: 26, ethnicity: "Samoan", registered_party: "Democrat", username: "Bill123", password: "123bill", role: 0)
@voter3 = Voter.create(name: "Dan", age: 27, ethnicity: "Irish", registered_party: "Democrat", username: "Bill123", password: "123bill", role: 0)
@voter4 = Voter.create(name: "Sarah", age: 28, ethnicity: "Samoan", registered_party: "Democrat", username: "Bill123", password: "123bill", role: 0)
@voter5 = Voter.create(name: "Steve", age: 29, ethnicity: "Irish", registered_party: "Democrat", username: "Bill123", password: "123bill", role: 0)
@voter6 = Voter.create(name: "Mike", age: 21, ethnicity: "Samoan", registered_party: "Democrat", username: "Bill123", password: "123bill", role: 0)
@voter7 = Voter.create(name: "Mitch", age: 22, ethnicity: "Irish", registered_party: "Democrat", username: "Bill123", password: "123bill", role: 0)
@voter8 = Voter.create(name: "Dave", age: 23, ethnicity: "Samoan", registered_party: "Democrat", username: "Bill123", password: "123bill", role: 0)
@voter9 = Voter.create(name: "Pancho", age: 45, ethnicity: "Irish", registered_party: "Democrat", username: "Bill123", password: "123bill", role: 0)
@voter10 = Voter.create(name: "Ren", age: 35, ethnicity: "Samoan", registered_party: "Democrat", username: "Bill123", password: "123bill", role: 0)
@voter11 = Voter.create(name: "Stimpy", age: 55, ethnicity: "Irish", registered_party: "Democrat", username: "Bill123", password: "123bill", role: 0)
@voter12 = Voter.create(name: "Chancho", age: 50, ethnicity: "Samoan", registered_party: "Democrat", username: "Bill123", password: "123bill", role: 0)
@voter13 = Voter.create(name: "Stu", age: 34, ethnicity: "Irish", registered_party: "Democrat", username: "Bill123", password: "123bill", role: 0)
@voter14 = Voter.create(name: "Martha", age: 20, ethnicity: "Samoan", registered_party: "Democrat", username: "Bill123", password: "123bill", role: 0)
@voter15 = Voter.create(name: "Tine", age: 31, ethnicity: "Irish", registered_party: "Democrat", username: "Bill123", password: "123bill", role: 0)
@voter16 = Voter.create(name: "Mickey", age: 42, ethnicity: "Samoan", registered_party: "Democrat", username: "Bill123", password: "123bill", role: 0)
@voter17 = Voter.create(name: "Liz", age: 19, ethnicity: "Irish", registered_party: "Democrat", username: "Bill123", password: "123bill", role: 0)
@voter18 = Voter.create(name: "Abdulla", age: 31, ethnicity: "Samoan", registered_party: "Democrat", username: "Bill123", password: "123bill", role: 0)
@voter19 = Voter.create(name: "Andrew", age: 31, ethnicity: "Irish", registered_party: "Democrat", username: "Bill123", password: "123bill", role: 0)
@voter20 = Voter.create(name: "Tara", age: 27, ethnicity: "Samoan", registered_party: "Democrat", username: "Bill123", password: "123bill", role: 0)
