require 'faker'

@voter1 = Voter.create(name: "Bill", age: 25, ethnicity: "Irish", registered_party: "Democrat", username: "Bill123", password: "123bill", role: 0)
@voter2 = Voter.create(name: "Bob", age: 26, ethnicity: "Samoan", registered_party: "Republican", username: "Bob123", password: "123bob", role: 0)
@voter3 = Voter.create(name: "Dan Richards", age: 27, ethnicity: "Irish", registered_party: "Independent", username: "Dan123", password: "123dan", role: 0)
@voter4 = Voter.create(name: "Sarah", age: 28, ethnicity: "Samoan", registered_party: "Democrat", username: "Sarah123", password: "123sarah", role: 0)
@voter5 = Voter.create(name: "Steve", age: 29, ethnicity: "Irish", registered_party: "Republican", username: "Steve123", password: "123steve", role: 0)
@voter6 = Voter.create(name: "Mike", age: 21, ethnicity: "Samoan", registered_party: "Independent", username: "Mike123", password: "123mike", role: 0)
@voter7 = Voter.create(name: "Mitch Wallace", age: 22, ethnicity: "Irish", registered_party: "Democrat", username: "Mitch123", password: "123mitch", role: 0)
@voter8 = Voter.create(name: "Dave", age: 23, ethnicity: "Samoan", registered_party: "Republican", username: "Dave123", password: "123dave", role: 0)
@voter9 = Voter.create(name: "Pancho", age: 45, ethnicity: "Irish", registered_party: "Independent", username: "Pancho123", password: "123pancho", role: 0)
@voter10 = Voter.create(name: "Ren", age: 35, ethnicity: "Samoan", registered_party: "Democrat", username: "Ren123", password: "123ren", role: 0)
@voter11 = Voter.create(name: "Stimpy", age: 55, ethnicity: "Irish", registered_party: "Republican", username: "Stimpy123", password: "123stimpy", role: 0)
@voter12 = Voter.create(name: "Chancho", age: 50, ethnicity: "Samoan", registered_party: "Independent", username: "Chancho123", password: "123chancho", role: 0)
@voter13 = Voter.create(name: "Stu", age: 34, ethnicity: "Irish", registered_party: "Democrat", username: "Stu123", password: "123stu", role: 0)
@voter14 = Voter.create(name: "Martha Lewis", age: 20, ethnicity: "Samoan", registered_party: "Republican", username: "Martha123", password: "123martha", role: 0)
@voter15 = Voter.create(name: "Tine", age: 31, ethnicity: "Irish", registered_party: "Independent", username: "Tine123", password: "123tine", role: 0)
@voter16 = Voter.create(name: "Mickey", age: 42, ethnicity: "Samoan", registered_party: "Democrat", username: "Mickey123", password: "123mickey", role: 0)
@voter17 = Voter.create(name: "Liz", age: 19, ethnicity: "Irish", registered_party: "Republican", username: "Liz123", password: "123liz", role: 0)
@voter18 = Voter.create(name: "Abdulla Qurat", age: 31, ethnicity: "Samoan", registered_party: "Independent", username: "Abdulla123", password: "123abdulla", role: 0)
@voter19 = Voter.create(name: "Andrew", age: 31, ethnicity: "Irish", registered_party: "Democrat", username: "Andrew123", password: "123andrew", role: 0)
@voter20 = Voter.create(name: "Tara", age: 27, ethnicity: "Samoan", registered_party: "Republican", username: "Tara123", password: "123tara", role: 0)
@voter21 = Voter.create(name: "Daniel Muli", age: 30, ethnicity: "Samoan", registered_party: "Democrat", username: "DanielRocks", password: "mamamia", role: 1)

@candidate1 = Candidate.create(voter_id: @voter3.id)
@candidate2 = Candidate.create(voter_id: @voter7.id)
@candidate3 = Candidate.create(voter_id: @voter14.id)
@candidate4 = Candidate.create(voter_id: @voter18.id)

@ballot1 = Ballot.create(name: "Colorado State Senate Election", office: "Senator")
@ballot2 = Ballot.create(name: "Colorado State Gubernatorial Election", office: "Governor")

@ballotcandidate1 = BallotCandidate.create(ballot_id: 1, candidate_id: 3)
@ballotcandidate1 = BallotCandidate.create(ballot_id: 1, candidate_id: 4)
@ballotcandidate1 = BallotCandidate.create(ballot_id: 2, candidate_id: 1)
@ballotcandidate1 = BallotCandidate.create(ballot_id: 2, candidate_id: 2)
